[[module.imports]]
path = "github.com/hbstack/header"

[[module.imports]]
path = "github.com/hbstack/socials"

[params.hugopress.modules.hb-header-socials.hooks.hb-header-panel]
weight = 1
cacheable = true
