[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hugopress.modules.hb-noscript.hooks.body-begin]
weight = 1
cacheable = true
