[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hbstack/snackbar"

[[module.imports]]
path = "github.com/hugomods/code-block-panel"

[[params.hb.modules.code-block-panel.js_resources]]
partial = "code-block-panel/assets/js-resource"
