[[module.imports]]
path = "github.com/hbstack/footer"

[[module.imports]]
path = "github.com/hbstack/socials"

[params.hugopress.modules.hb-footer-socials.hooks.hb-footer-site-info-end]
weight = 1
cacheable = true
